#!/usr/bin/env python3
"""
Script to generate bookmarks/index.qmd from _data/bookmarks.yml

Usage:
    /home/theodore/progress/.venv/bin/python _scripts/generate-bookmarks.py
    
    Or activate venv first:
    source .venv/bin/activate
    python _scripts/generate-bookmarks.py

This will regenerate bookmarks/index.qmd with all bookmark cards.
To add/remove cards, edit _data/bookmarks.yml instead.
"""

import yaml
from pathlib import Path

def load_bookmarks_data():
    """Load bookmark cards data from YAML file"""
    data_file = Path("_data/bookmarks.yml")
    with open(data_file, 'r') as f:
        data = yaml.safe_load(f)
    return data['bookmarks']

def generate_card_html(bookmark):
    """Generate HTML for a single bookmark card"""
    # If the bookmark has a `colors` mapping, build inline style attributes for
    # the elements so colors can be controlled from _data/bookmarks.yml using
    # intuitive variable names (sidebar_bg, sidebar_border, label_text,
    # overlay_bg, overlay_text, footer_bg, footer_text). We keep the existing
    # CSS classes as fallbacks.
    colors = bookmark.get('colors', {}) or {}

    def style_from(mapping):
        """Given a dict of css property->value, return a style attribute string or empty string."""
        if not mapping:
            return ''
        parts = [f"{k}: {v};" for k, v in mapping.items() if v is not None]
        if not parts:
            return ''
        return ' style="' + ' '.join(parts) + '"'

    # Build style attrs
    sidebar_style = style_from({
        'background': colors.get('sidebar_bg'),
        'border-left-color': colors.get('sidebar_border')
    })

    label_style = style_from({
        'color': colors.get('label_text')
    })

    overlay_style = style_from({
        'background': colors.get('overlay_bg'),
        'color': colors.get('overlay_text')
    })

    footer_style = style_from({
        'background': colors.get('footer_bg'),
        'color': colors.get('footer_text')
    })

    # card-description text color (if provided)
    description_style = style_from({
        'color': colors.get('description_text')
    })

    return f'''    <div class="bookmark-card">
      <a href="{bookmark['id']}/" class="card-main-link">
        <div class="card-main">
          <div class="category-sidebar {bookmark.get('color_light','') }"{sidebar_style}>
            <div class="category-text {bookmark.get('color_dark','') }"{label_style}>{bookmark['title']}</div>
          </div>
          <div class="card-image-wrapper">
            <img src="{bookmark['image']}" alt="{bookmark['title']}" class="card-image">
            <div class="view-link-overlay {bookmark.get('color_accent','') }"{overlay_style}>View all bookmarks</div>
          </div>
        </div>
      </a>
      <div class="card-footer {bookmark.get('color_dark','') }"{footer_style}>
        <div class="featuring-label">Collected</div>
        <div class="card-description"{description_style}>{bookmark['description']}</div>
      </div>
    </div>
'''

def generate_index_qmd():
    """Generate the complete bookmarks/index.qmd file"""
    bookmarks = load_bookmarks_data()
    
    # Generate all card HTML
    cards_html = '\n'.join(generate_card_html(b) for b in bookmarks)
    
    # Generate preload links for images
    preload_links = '\n'.join(
        f'    <link rel="preload" as="image" href="{b["image"]}">'
        for b in bookmarks
    )
    
    # Complete index.qmd content
    content = f'''---
title: ""
page-layout: custom
toc: false
css: ../_assets/css/bookmarks.css
---

<!-- 
  THIS FILE IS AUTO-GENERATED by _scripts/generate-bookmarks.py
  Do not edit this file directly!
  To add/remove/edit bookmark cards, edit _data/bookmarks.yml
  Then run: python3 _scripts/generate-bookmarks.py
-->

```{{=html}}
<!-- Preload images for faster loading -->
{preload_links}

<script>
document.addEventListener('DOMContentLoaded', function() {{
  const container = document.querySelector('.bookmarks-container');
  
  // Horizontal scroll on vertical wheel
  // Convert vertical wheel into horizontal scroll while the container can
  // scroll horizontally. When the container is at either end, allow the
  // event to bubble so the page can scroll vertically (show footer/other
  // content). This preserves natural overscroll behavior.
  container.addEventListener('wheel', function(e) {{
    if (e.deltaY === 0) return; // nothing to do

    const scrollLeft = container.scrollLeft;
    const maxScrollLeft = container.scrollWidth - container.clientWidth;
    const atLeft = scrollLeft <= 0;
    const atRight = scrollLeft >= maxScrollLeft - 1; // small epsilon

    // If scrolling down (deltaY > 0) we want to move right; if there's
    // room to scroll right, consume the event and translate to horizontal.
    if (e.deltaY > 0) {{
      if (!atRight) {{
        e.preventDefault();
        container.scrollLeft = Math.min(maxScrollLeft, scrollLeft + e.deltaY);
      }} // else allow event to bubble (page scroll)
    }} else {{
      // Scrolling up (deltaY < 0) -> move left
      if (!atLeft) {{
        e.preventDefault();
        container.scrollLeft = Math.max(0, scrollLeft + e.deltaY);
      }} // else allow event to bubble (page scroll)
    }}
  }}, {{ passive: false }});
}});
</script>

<div class="bookmarks-container">
  <div class="bookmarks-scroll">
    
{cards_html}
    
  </div>
</div>
```
'''
    
    # Write to file
    output_file = Path("bookmarks/index.qmd")
    with open(output_file, 'w') as f:
        f.write(content)
    
    print(f"✓ Generated {output_file}")
    print(f"  Created {len(bookmarks)} bookmark cards")

if __name__ == "__main__":
    generate_index_qmd()
